/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/TQQb1PydUxI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

"use client";

import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { SelectValue, SelectTrigger, SelectItem, SelectGroup, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { useState,useEffect } from "react"

export function Trans() {

  const [content, setContent] = useState('');
  const [language, setLanguage] = useState('English')
  const [translated, setTranslated] = useState('this is translated text')
  const [support, setSupported] = useState(false)

  useEffect(() => {
    const ai = (window as any).ai
    const supportsOnDevice = 'ai' in window &&  ai.canCreateTextSession();
    if (!supportsOnDevice) {
      setSupported(false)
      return;
    }
    setSupported(true)
  })




  async function handleTrans(e) {
    e.preventDefault();
    console.log(`content: ${content}\n`)
    console.log(`language: ${language}\n`)
    console.log(`translated: ${translated}`)

    const ai = (window as any).ai 

    const supportsOnDevice = 'ai' in window &&  ai.canCreateTextSession();
    if (!supportsOnDevice) {
      setSupported(false)
      return;
    }

    const session  = await ai.createTextSession()
    const result = await session.prompt(`You are a translation expert, please help me translate the following sentence  into ${language}:  ${content}`)
    setTranslated(result)    
  }


  return (
    <div className="flex flex-col items-center justify-center h-screen gap-8">
        <div className="text-center">
        <h1 className="text-3xl font-bold mb-4">Translate Text Using Chrome AI </h1>
        { !support &&
        <p className="text-red-500 font-bold">Your Chrome is not supported, see https://x.com/leeoxiang/status/1799334729365487869</p>
        }
       
      </div>
      <div className="w-full max-w-md">
        <form className="grid gap-4">
          <div className="grid gap-1.5">
            <Label htmlFor="text">Enter text to translate</Label>
            <Textarea className="h-24 resize-none" id="translate-text" name="text" placeholder="Type your text here..."  value={content}  onChange={e => setContent(e.target.value)}/>
          </div>
          <div className="grid gap-1.5">
            <Label htmlFor="language">Select target language</Label>
            <Select name="language" value={language}  onValueChange={setLanguage} >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Choose a language" />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectItem value="English">English</SelectItem>
                  <SelectItem value="Spanish">Spanish</SelectItem>
                  <SelectItem value="French">French</SelectItem>
                  <SelectItem value="German">German</SelectItem>
                  <SelectItem value="Chinese">Chinese</SelectItem>
                  <SelectItem value="Japanese">Japanese</SelectItem>
                  <SelectItem value="Arabic">Arabic</SelectItem>
                </SelectGroup>
              </SelectContent>
            </Select>
          </div>
          <Button className="mt-2" onClick={handleTrans}>
            Translate
          </Button>
        </form>
      </div>
      <div className="w-full max-w-md space-y-2">
        <h3 className="text-lg font-medium">Translated Text:</h3>
        <div id="ranslated-text" className="rounded-md bg-gray-100 p-4 text-gray-800 dark:bg-gray-800 dark:text-gray-200">
          {translated}
        </div>
      </div>
    </div>
  )
}
